<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>bobas.businessobjectscommon</artifactId>
  <name>bobas.businessobjectscommon</name>
  <url>https://colorcoding.org/ibas/bobas/</url>
  <parent>
    <groupId>org.colorcoding.ibas</groupId>
    <artifactId>bobas.businessobjectscommon.parent</artifactId>
    <version>0.2.0</version>
  </parent>
  <organization>
    <name>Color-Coding Studio</name>
    <url>https://colorcoding.org</url>
  </organization>
  <properties>
    <jakarta.annotation.version>3.0.0</jakarta.annotation.version>
    <jakarta.xml.bind.version>4.0.2</jakarta.xml.bind.version>
    <jaxb.runtime.version>4.0.9</jaxb.runtime.version>
    <junit.version>4.13.2</junit.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>${jakarta.xml.bind.version}</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>${jaxb.runtime.version}</version>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>${jakarta.annotation.version}</version>
    </dependency>
  </dependencies>
</project>
